apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cvat
spec:
  selector:
    matchLabels:
      app: cvat # has to match .spec.template.metadata.labels
  serviceName: "cvat"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: cvat # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
{{ if .Values.workloads }}
{{ toYaml .Values.workloads | indent 6 }}
{{ end}}
      containers:
      - name: cvat
        image: openvino/cvat_server:v{{ .Chart.AppVersion }}
        env:
{{ template "cvat-helm.postgres-env" . }}
        - name: "DJANGO_MODWSGI_EXTRA_ARGS"
          value: ''
        - name: "ALLOWED_HOSTS"
          value: '*'
        - name: "CVAT_REDIS_HOST"
          value: 'cvat-redis'
        - name: ADAPTIVE_AUTO_ANNOTATION
          value: 'false'
        - name: CVAT_SHARE_URL
          value: 'Mounted data'
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
          - mountPath: "/home/django/data"
            name: cvat-data
          - mountPath: "/home/django/keys"
            name: cvat-keys
          - mountPath: "/home/django/logs"
            name: cvat-logs
          - mountPath: "/home/django/share"
            name: cvat-share
            readOnly: true

      volumes:
        - name: cvat-data
          persistentVolumeClaim:
            claimName: cvat-data
        - name: cvat-keys
          persistentVolumeClaim:
            claimName: cvat-keys
        - name: cvat-logs
          persistentVolumeClaim:
            claimName: cvat-logs
        - name: cvat-share
          persistentVolumeClaim:
            claimName: {{ .Values.volume.share.name }}

---
apiVersion: v1
kind: Service
metadata:
  name: cvat
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: cvat
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvat-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
{{ if .Values.volume.data.storageClassName }}
  storageClassName: {{ .Values.volume.data.storageClassName }}
{{ end }}
  resources:
    requests:
      storage: {{ .Values.volume.data.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvat-keys
spec:
{{ if .Values.volume.keys.storageClassName }}
  storageClassName: {{ .Values.volume.keys.storageClassName }}
{{ end }}
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.volume.keys.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvat-logs
spec:
{{ if .Values.volume.logs.storageClassName }}
  storageClassName: {{ .Values.volume.logs.storageClassName }}
{{ end }}
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.volume.logs.size }}
{{ if .Values.volume.share.create }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.share.name }}
spec:
{{ if .Values.volume.share.storageClassName }}
  storageClassName: {{ .Values.volume.share.storageClassName }}
{{ end }}
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.volume.share.size }}
{{ end }}