{{ if .Values.ingress.enabled }}
{{ if .Values.ingress.clusterIssuer }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cvat-ingress
spec:
  secretName: cvat-ingress
  issuerRef:
    name: {{ .Values.ingress.clusterIssuer }}
    kind: ClusterIssuer
  commonName: {{ .Values.ingress.host }}
  dnsNames:
  - {{ .Values.ingress.host }}
---
{{ end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cvat-ingress
  annotations:
{{ if semverCompare "<1.21-0" .Capabilities.KubeVersion.GitVersion }}
      kubernetes.io/ingress.class: {{ .Values.ingress.ingressClassName }}
{{ end }}
      nginx.ingress.kubernetes.io/proxy-body-size: 900m
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-origin: "*"
      nginx.ingress.kubernetes.io/cors-allow-headers: X-XSRF-TOKEN,Accept,Accept-Encoding,Accept-Language,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,Origin,Connection,Content-Length,Content-Type,Host,Referer,User-Agent
      nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
      nginx.ingress.kubernetes.io/use-regex: "true"
spec:
{{ if semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
{{ end }}
{{ if .Values.ingress.clusterIssuer }}
  tls:
  - hosts:
      - {{ .Values.ingress.host }}
    secretName: cvat-ingress
{{ end }}
  rules:
  - http:
        paths:
          - path: "/(api|git|opencv|analytics|static|documentation|django-rq|admin)(.*)"
            pathType: ImplementationSpecific
            backend:
                service: 
                    name: cvat
                    port:
                        number: 8080
          - path: "/.*"
            pathType: ImplementationSpecific
            backend:
                service: 
                    name: cvat-ui
                    port:
                        number: 80
{{ if .Values.ingress.host }}
    host: {{ .Values.ingress.host }}
{{ end }}

#    proxy_pass_header       X-CSRFToken;
#    proxy_set_header        Host $http_host;
#    proxy_pass_header       Set-Cookie;
{{ end }}