{{ if .Values.superUser.create }}
apiVersion: batch/v1
kind: Job
metadata:
  name: cvat-init-create-users
spec:
  template:
    metadata:
      labels:
        app: cvat-init-create-users # has to match .spec.selector.matchLabels
    spec:
      restartPolicy: OnFailure
      containers:
      - name: cvat
        image: openvino/cvat_server
        env:
        - name: "CVAT_REDIS_HOST"
          value: 'cvat-redis'
        - name: CVAT_POSTGRES_HOST
          value: 'cvat-db'
        command: ["/bin/sh", "-c"]
        args:
            - python3 ~/manage.py createsuperuser --username "{{ .Values.superUser.username }}" --email "{{ .Values.superUser.email }}"  --noinput &&
              echo "from django.contrib.auth.models import User; u=User.objects.get(username='{{ .Values.superUser.username }}'); u.set_password('{{ .Values.superUser.initialPassword }}'); u.save()" | python3 ~/manage.py shell
{{ end }}
