apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cvat-ingress
  annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
spec:
{{ if .Values.ingress.clusterIssuer }}
  tls:
  - hosts:
      - {{ .Values.ingress.host }}
    secretName: cvat-ingress
{{ end }}
  rules:
  - http:
        paths:
          - path: "/(api|git|opencv|analytics|static|documentation|django-rq|admin)(.*)"
            pathType: ImplementationSpecific
            backend:
                service: 
                    name: cvat
                    port:
                        number: 8080
          - path: "/.*"
            pathType: ImplementationSpecific
            backend:
                service: 
                    name: cvat-ui
                    port:
                        number: 80
{{ if .Values.ingress.host }}
    host: {{ .Values.ingress.host }}
{{ end }}

#    proxy_pass_header       X-CSRFToken;
#    proxy_set_header        Host $http_host;
#    proxy_pass_header       Set-Cookie;


